[options]
HoldPkg     = pacman glibc
Architecture = x86_64
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional
NoExtract   =

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

[custom]
SigLevel = Never
Server = file:///tmp/mulch-custom-repo